### ISSUE TITLE
Create a "Designer collaborator guide"

### ISSUE THREAD

**Issue by fjfdeztoro** [Karumi/project-quality-assurance#4]
Based on this comment https://github.com/Karumi/project-quality-assurance/pull/3#discussion_r168504176 we should create an entry about what we expect from a feature in design terms like 

- Color palette
- Text Styles (font, size, ...)
- Button Styles ( Borders, background color, behaviour on interaction, ..)
- Notifications 
- Error Cases
- Loading cases.
- ...

The main idea about it is to set up front the design idioms in order to come up with code that can be reusable.

**Comment by pedrovgs** [comment]
@davideme can we close this now we've merged your PR?
