### ISSUE TITLE
Lint tool [Android]

### ISSUE THREAD

**Issue by goonerDroid** [Karumi/project-quality-assurance#7]
*KTLint is great Lint tool for a project written in Kotlin.Any suggestions which lint you guys use for Android project written in Java?*</td>

**Comment by Serchinastico** [comment]
We've been using [Checklist](http://checkstyle.sourceforge.net/) but I know there are plenty of them! We often start with [Google's ruleset](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) or [Square's one](https://github.com/square/java-code-styles/blob/master/configs/codestyles/SquareAndroid.xml) and change them as soon as we find something is missing/getting in the way.

**Comment by goonerDroid** [comment]
Would be great if you guys can update in your Readme.md for Android.Thanks!
